// js/views/shopping.js — 01 Sep 2026 v8
// Replaces the Phase 2 stub, whole.
//
// The list is generated by diffing the weekly plan against the pantry —
// principle 5. If it makes you open a cupboard and then edit the list, it
// has failed however complete it looks.
//
// ---- This screen is used in a shop ----
// No signal, one hand, moving. So ticking is optimistic and queued, the
// button is never disabled mid-write, targets are full size, and the list
// is ordered by AISLE rather than alphabetically — walking you through the
// shop in order is the difference between a list you use and one you ignore.
//
// ---- One food, one entry, two lines ----
// The same thing can arrive twice: once from the plan, once as a staple.
// The ROWS stay separate because `source` is what makes regeneration safe.
// Only the rendering is grouped, each line labelled with where it came
// from, and a total offered only when the units match.
//
// ---- Regeneration says what it will destroy, first ----
// It replaces meal-plan lines you have not ticked. Anything marked have or
// bought survives, and so do staples and holiday items. The confirm states
// the numbers before anything is deleted.

import {
  listItems, addItem, setStatus, removeItem, replaceGeneratedItems,
  countReplaceable, countProtected, groupByFood, aisleRank, flushQueued,
  SOURCE_LABELS, STATUS_LABELS
} from '../data/shopping.js';
import { listPlan } from '../data/mealPlan.js';
import { listIngredients } from '../data/meals.js';
import { listStock } from '../data/pantry.js';
import { listFoods, categoryLabel, groupByCategory } from '../data/foods.js';
import { computeShortfall } from '../lib/shortfall.js';
import { formatQuantity, formatPackQuantity } from '../lib/units.js';
import { isOffline } from '../lib/net.js';
import { confirmDialog } from '../components/confirmDialog.js';
import { openDetailSheet } from '../components/detailSheet.js';
import { showToast } from '../components/toast.js';
import { announce } from '../lib/a11y.js';
import { restockFromPurchase, describeRestock, RESTOCK } from '../data/restock.js';
import { getHousehold } from '../data/household.js';
import { emptyState } from '../components/emptyState.js';
import { addStarterStaples, addDueStaples } from '../data/staples.js';

import { el, field } from '../lib/dom.js';
function todayIso() {
  return new Date().toISOString().slice(0, 10);
}

/** The cycle a shop actually follows. */
function nextStatus(current) {
  if (current === 'needed') return 'have';
  if (current === 'have') return 'bought';
  return 'needed';
}

export function render(mountEl) {
  const controller = new AbortController();
  const { signal } = controller;
  let destroyed = false;

  let items = [];
  let foods = [];
  let hideDone = false;

  mountEl.appendChild(el('h1', { text: 'Shopping list' }));

  const offlineNote = el('p', { class: 'field-hint' });
  offlineNote.hidden = true;
  mountEl.appendChild(offlineNote);

  function paintOfflineNote() {
    const off = isOffline();
    offlineNote.hidden = !off;
    if (off) {
      offlineNote.textContent =
        'You are offline. Ticking things off still works — it saves here and syncs when you are back.';
    }
  }

  const actions = el('div', { class: 'filter-row' });
  const regenerateBtn = el('button', {
    type: 'button', class: 'btn btn-primary', text: 'Build from the plan'
  });
  const filterBtn = el('button', { type: 'button', class: 'btn', text: 'Filter' });
  actions.append(regenerateBtn, filterBtn);
  mountEl.appendChild(actions);

  const summary = el('p', { class: 'field-hint', role: 'status' });
  summary.setAttribute('aria-live', 'polite');
  mountEl.appendChild(summary);

  const listWrap = el('div');
  mountEl.appendChild(listWrap);

  function paintFilterButton() {
    filterBtn.textContent = hideDone ? 'Filter (1)' : 'Filter';
    filterBtn.setAttribute('aria-label', hideDone
      ? 'Filter the list, 1 filter on' : 'Filter the list');
  }

  filterBtn.addEventListener('click', () => {
    openDetailSheet({
      title: 'Filter the list',
      subtitle: 'Nothing is deleted — this only changes what is shown.',
      returnFocusTo: filterBtn,
      build: (body, { close }) => {
        const row = el('div', { class: 'field field-checkbox' });
        const cb = el('input', { id: 'shopping-hide-done', type: 'checkbox' });
        cb.checked = hideDone;
        const label = el('label', { for: cb.id, text: 'Hide anything already got' });
        cb.addEventListener('change', () => {
          hideDone = cb.checked;
          paintFilterButton();
          renderList();
        }, { signal });
        row.append(cb, label);
        body.appendChild(row);

        const done = el('button', { type: 'button', class: 'btn', text: 'Done' });
        done.addEventListener('click', () => close(), { signal });
        body.appendChild(done);
      }
    });
  }, { signal });

  // ---- Regeneration --------------------------------------------------

  regenerateBtn.addEventListener('click', async () => {
    const [replaceable, protectedCount] = await Promise.all([countReplaceable(), countProtected()]);
    if (destroyed) return;
    if (!replaceable.ok || !protectedCount.ok) {
      console.error('Could not count the list before rebuilding:',
        replaceable.error || protectedCount.error);
      showToast("Couldn't check the list first — try again.");
      return;
    }

    // COUNT BEFORE ACTING: say what will be destroyed, in numbers, before
    // destroying it.
    const willReplace = replaceable.data;
    const willKeep = protectedCount.data;
    const message = willReplace === 0 && willKeep === 0
      ? 'This works out what your weekly plan needs that the pantry does not already have.'
      : 'This rebuilds the list from your weekly plan. '
        + `${willReplace} item${willReplace === 1 ? '' : 's'} you have not ticked will be replaced`
        + `${willKeep > 0 ? `, and ${willKeep} you have marked as have or bought will be kept` : ''}. `
        + 'Staples and holiday items are never touched.';

    const confirmed = await confirmDialog({
      title: 'Rebuild from the weekly plan?',
      message,
      confirmLabel: 'Rebuild',
      cancelLabel: 'Leave it'
    });
    if (!confirmed || destroyed) return;

    regenerateBtn.disabled = true;
    const [plan, ingredients, pantry, foodList] = await Promise.all([
      listPlan(), listIngredients(), listStock(), listFoods()
    ]);
    // Phase 20: who is eating scales the list. A failed household read is
    // not fatal — an empty member list falls back to each meal's own
    // default_serves, which is exactly the pre-Phase-20 behaviour.
    const household = await getHousehold();
    if (destroyed) return;

    if (!plan.ok || !ingredients.ok || !pantry.ok || !foodList.ok) {
      regenerateBtn.disabled = false;
      console.error('Could not gather what the rebuild needs:',
        plan.error || ingredients.error || pantry.error || foodList.error);
      showToast("Couldn't read your plan and pantry — check your connection and try again.");
      return;
    }

    const { items: shortfall, skipped } = computeShortfall({
      plan: plan.data,
      ingredients: ingredients.data,
      pantry: pantry.data,
      foods: foodList.data,
      todayISO: todayIso(),
      householdMembers: household.ok ? household.data.members : []
    });

    const result = await replaceGeneratedItems(shortfall);
    regenerateBtn.disabled = false;
    if (destroyed) return;

    if (!result.ok) {
      console.error('Rebuild failed:', result.error);
      showToast(result.stage === 'insert'
        // The old rows are already gone. Say what to do rather than leaving
        // the user to wonder why the list emptied.
        ? 'The old list was cleared but the new one failed to save. Press Build again.'
        : "Couldn't rebuild the list — nothing was changed.");
      await load();
      return;
    }

    announce(shortfall.length === 0
      ? 'Nothing needed — the pantry already covers your plan.'
      : `${shortfall.length} thing${shortfall.length === 1 ? '' : 's'} added to the list.`);
    for (const skip of skipped) showToast(`${skip.meal} was left out — ${skip.reason}.`);
    await load();
  }, { signal });

  // ---- The list ------------------------------------------------------

  function renderList() {
    listWrap.replaceChildren();

    if (items.length === 0) {
      // Phase 28 + 22. The list builds itself from the plan now, so the
      // action is the thing that CAUSES a list, not the rebuild button.
      listWrap.appendChild(emptyState({
        body: 'Your shopping list fills itself in from what you plan to eat, '
          + 'minus what is already in the cupboard.',
        actionLabel: 'Plan the week',
        actionHref: '#/plan-week',
        why: 'You can also add staples below at any time.'
      }));

      // Phase 25. The other half of a shopping list: the things no meal
      // plan will ever ask for. Offered once on an empty list, never
      // automatic — a list that fills itself with things you did not ask
      // for is worse than an empty one.
      const starter = el('button', {
        type: 'button', class: 'btn', text: 'Add my usual household staples'
      });
      starter.addEventListener('click', async () => {
        starter.disabled = true;
        starter.textContent = 'Adding…';
        const result = await addStarterStaples();
        if (destroyed) return;
        if (!result.ok) {
          starter.disabled = false;
          starter.textContent = 'Add my usual household staples';
          showToast('Those could not be added. Check your connection.');
          return;
        }
        showToast(`${result.added} staple${result.added === 1 ? '' : 's'} added. `
          + 'Remove anything you do not buy.');
        await load();
      }, { signal });
      listWrap.appendChild(starter);
      listWrap.appendChild(el('p', {
        class: 'field-hint',
        text: 'Toilet roll, washing up liquid, toothpaste and the like. '
          + 'Remove anything that is not yours.'
      }));
      summary.textContent = '';
      return;
    }

    const visible = hideDone ? items.filter((item) => item.status === 'needed') : items;
    if (visible.length === 0) {
      listWrap.appendChild(el('p', { text: 'Everything on the list is got. Nothing left to show.' }));
    }

    const grouped = groupByFood(visible);
    const byCategory = new Map();
    for (const entry of grouped) {
      const category = (entry.food && entry.food.category) || 'other';
      if (!byCategory.has(category)) byCategory.set(category, []);
      byCategory.get(category).push(entry);
    }

    // AISLE ORDER, never alphabetical.
    const ordered = [...byCategory.entries()].sort((a, b) => aisleRank(a[0]) - aisleRank(b[0]));
    for (const [category, entries] of ordered) {
      // A real heading carrying its count, so the list is navigable by
      // heading rather than by scrolling.
      listWrap.appendChild(el('h2', {
        class: 'group-heading',
        text: `${categoryLabel(category)} (${entries.length})`
      }));
      const list = el('ul', { class: 'shopping-rows' });
      for (const entry of entries) list.appendChild(buildEntry(entry));
      listWrap.appendChild(list);
    }

    const outstanding = items.filter((item) => item.status === 'needed').length;
    summary.textContent = outstanding === 0
      ? `${items.length} thing${items.length === 1 ? '' : 's'}, all got.`
      : `${outstanding} still to get, of ${items.length}.`;
  }

  /** One food, however many rows it arrived as. */
  function buildEntry(entry) {
    const item = el('li', { class: 'shopping-entry' });
    const name = (entry.food && entry.food.name) || 'Unknown';

    const head = el('div', { class: 'shopping-entry-head' });
    head.appendChild(el('span', { class: 'shopping-entry-name', text: name }));
    // A total ONLY when the units match. Grams are never added to items.
    if (entry.total != null && entry.unit) {
      head.appendChild(el('span', {
        class: 'shopping-entry-total',
        text: formatPackQuantity(entry.total, entry.unit, entry.food || null)
      }));
    }
    item.appendChild(head);

    const lines = el('ul', { class: 'shopping-lines' });
    for (const line of entry.lines) {
      lines.appendChild(buildLine(line, name, entry.lines.length > 1));
    }
    item.appendChild(lines);

    // One tap ticks every line under this food.
    if (entry.lines.length > 1) {
      const anyNeeded = entry.lines.some((line) => line.status === 'needed');
      const all = el('button', { type: 'button', class: 'btn btn-small' });
      all.textContent = anyNeeded ? 'Got all of it' : 'Still need it';
      all.setAttribute('aria-label',
        `${anyNeeded ? 'Mark every line of' : 'Mark as still needed:'} ${name}`);
      all.addEventListener('click', async () => {
        for (const line of entry.lines) {
          await changeStatus(line, anyNeeded ? 'bought' : 'needed', null, name);
        }
        await load();
      }, { signal });
      item.appendChild(all);
    }

    return item;
  }

  function buildLine(line, foodName, showSource) {
    const row = el('li', { class: 'shopping-line' });

    const text = el('span', { class: 'shopping-line-text' });
    text.appendChild(el('span', {
      text: line.qty_needed == null
        ? 'Amount not set'
        : formatPackQuantity(line.qty_needed, line.unit, line.foods || null)
    }));
    // Two rows for one food look like a bug unless the reason is stated.
    if (showSource) {
      text.appendChild(el('span', {
        class: 'shopping-line-source',
        text: SOURCE_LABELS[line.source] || line.source
      }));
    }
    row.appendChild(text);

    const toggle = el('button', { type: 'button', class: 'btn check-toggle' });
    paintToggle(toggle, line, foodName);
    toggle.addEventListener('click', () => {
      changeStatus(line, nextStatus(line.status), toggle, foodName);
    }, { signal });
    row.appendChild(toggle);

    const remove = el('button', { type: 'button', class: 'btn btn-small btn-danger', text: 'Remove' });
    remove.setAttribute('aria-label', `Remove ${foodName} from the list`);
    remove.addEventListener('click', async () => {
      const result = await removeItem(line.id);
      if (destroyed) return;
      if (!result.ok) {
        console.error('Failed to remove a list item:', result.error);
        showToast("Couldn't remove that — try again.");
        return;
      }
      await load();
      if (destroyed) return;
      // Phase 22. An undo, not a confirm. A confirm asks you to predict
      // your own mistake before making it; undo lets you notice it a moment
      // later, which is how mistakes actually get noticed.
      showToast(`${foodName} removed.`, {
        undo: async () => {
          const back = await addItem({
            food_id: line.food_id,
            qty_needed: line.qty_needed,
            unit: line.unit,
            source: line.source
          });
          if (destroyed) return;
          if (!back.ok) { showToast("That couldn't be put back."); return; }
          announce(`${foodName} put back on the list.`);
          await load();
        }
      });
    }, { signal });
    row.appendChild(remove);

    return row;
  }

  function paintToggle(btn, line, foodName) {
    const label = STATUS_LABELS[line.status] || line.status;
    btn.textContent = label;
    // State in a word and in aria-pressed, never colour alone.
    btn.setAttribute('aria-pressed', String(line.status !== 'needed'));
    btn.setAttribute('aria-label',
      `${foodName}: ${label}. Tap for ${STATUS_LABELS[nextStatus(line.status)]}.`);
  }

  /**
   * Optimistic. The tap counts immediately and the write runs behind it.
   * The button is NEVER disabled — this happens in a shop, one-handed, and
   * a dead control reads as a crash.
   */
  async function changeStatus(line, status, btn, foodName) {
    const before = line.status;
    line.status = status;
    if (btn) paintToggle(btn, line, foodName);

    const result = await setStatus(line.id, status);
    if (destroyed) return;
    if (!result.ok) {
      line.status = before;
      if (btn) paintToggle(btn, line, foodName);
      console.error('Failed to change a list status:', result.error);
      showToast("That didn't save — tap it again.");
      return;
    }
    if (result.queued) {
      announce('Saved on this device. It will sync when you are back online.');
    }

    // ---- Phase 11: bought means it is in the cupboard ----
    // Without this the list knew you had bought it and the pantry did not,
    // so next week's shortfall asked you to buy it again.
    //
    // Deliberately NOT done for a queued write: the restock is a second
    // write to a second table, and firing it against a status that has not
    // landed yet would put stock in the cupboard for a purchase the server
    // never heard about. It replays with the queue instead.
    if (status === 'bought' && before !== 'bought' && !result.queued) {
      await applyRestock(line, foodName);
      if (destroyed) return;
    }

    if (hideDone) renderList();
  }

  /**
   * Puts a bought line into the pantry and says what happened.
   *
   * Failures here are reported, never rolled back onto the status. You did
   * buy the thing; a pantry write that did not land does not make that
   * untrue, and un-ticking it under your thumb in a shop would be worse
   * than the gap it was trying to fix.
   */
  async function applyRestock(line, foodName) {
    const food = foods.find((f) => f.id === line.food_id) || {};
    const done = await restockFromPurchase(line, food);
    if (destroyed) return;

    if (!done.ok) {
      console.error('Could not restock from a purchase:', done.error);
      showToast(`${foodName} is ticked off, but the pantry did not update.`);
      return;
    }

    const message = describeRestock(done.outcome, {
      foodName,
      listUnit: line.unit,
      stockUnit: done.data ? done.data.unit : null
    });

    // A mismatch needs reading, so it gets the announcement and a toast.
    // The ordinary cases are quiet: you are in a shop and a toast per item
    // would be its own kind of noise.
    if (done.outcome === RESTOCK.UNIT_MISMATCH) {
      showToast(message);
      announce(message);
    } else {
      announce(message);
    }
  }

  // ---- Add a staple by hand ------------------------------------------

  const addForm = el('form');
  addForm.setAttribute('aria-label', 'Add something to the list');
  const foodSelect = el('select', { id: 'shopping-food' });
  const qtyInput = el('input', {
    id: 'shopping-qty', type: 'number', min: '0', step: 'any', inputmode: 'decimal'
  });
  const qtyHint = el('p', {
    class: 'field-hint', id: 'shopping-qty-hint',
    text: 'Leave blank if you just need "some".'
  });
  qtyInput.setAttribute('aria-describedby', qtyHint.id);
  const unitSelect = el('select', { id: 'shopping-unit' });
  for (const [value, label] of [['item', 'items'], ['g', 'grams (g)'], ['ml', 'millilitres (ml)']]) {
    unitSelect.appendChild(el('option', { value, text: label }));
  }
  const addError = el('p', { class: 'field-error', role: 'alert' });
  addError.hidden = true;
  const addSubmit = el('button', {
    type: 'submit', class: 'btn btn-primary btn-block', text: 'Add to list'
  });

  addForm.append(
    el('h2', { text: 'Add a staple' }),
    el('p', {
      class: 'field-hint',
      text: 'Things you always buy. These are never touched when the list is rebuilt.'
    }),
    field('Item', foodSelect),
    field('How much', qtyInput, qtyHint),
    field('Measured in', unitSelect),
    addError,
    addSubmit
  );
  mountEl.appendChild(addForm);

  addForm.addEventListener('submit', async (event) => {
    event.preventDefault();
    addError.hidden = true;
    if (!foodSelect.value) {
      addError.textContent =
        'Choose an item. If the list is empty, add it under "Things you buy" first.';
      addError.hidden = false;
      foodSelect.focus();
      return;
    }
    addSubmit.disabled = true;
    const result = await addItem({
      food_id: foodSelect.value,
      qty_needed: qtyInput.value,
      unit: unitSelect.value,
      source: 'usual'
    });
    addSubmit.disabled = false;
    if (destroyed) return;
    if (!result.ok) {
      addError.textContent = isOffline()
        ? 'Adding needs a connection. Ticking things off still works.'
        : (result.error && result.error.message) || "Couldn't add that — try again.";
      addError.hidden = false;
      return;
    }
    qtyInput.value = '';
    announce('Added to the list.');
    await load();
  }, { signal });

  function rebuildFoodSelect() {
    const chosen = foodSelect.value;
    foodSelect.replaceChildren(el('option', {
      value: '',
      text: foods.length === 0 ? 'Nothing to choose yet' : 'Choose an item'
    }));
    for (const group of groupByCategory(foods)) {
      const optgroup = document.createElement('optgroup');
      optgroup.label = group.label;
      for (const food of group.foods) {
        const option = el('option', { value: food.id, text: food.name });
        if (food.id === chosen) option.selected = true;
        optgroup.appendChild(option);
      }
      foodSelect.appendChild(optgroup);
    }
  }

  // ---- Loading -------------------------------------------------------

  async function load() {
    const [listResult, foodResult] = await Promise.all([listItems(), listFoods()]);
    if (destroyed) return;
    if (!listResult.ok) {
      console.error('Failed to load the shopping list:', listResult.error);
      listWrap.replaceChildren(el('p', {
        class: 'view-status',
        text: "Couldn't load your list. Check your connection, then reload this page."
      }));
      return;
    }
    items = listResult.data;
    foods = foodResult.ok ? foodResult.data : [];
    rebuildFoodSelect();
    renderList();
  }

  paintFilterButton();
  paintOfflineNote();

  function onConnectionChange() {
    if (destroyed) return;
    paintOfflineNote();
    if (!isOffline()) {
      flushQueued()
        .then(() => { if (!destroyed) load(); })
        .catch((err) => console.error('Could not replay queued shopping changes:', err));
    }
  }
  window.addEventListener('online', onConnectionChange);
  window.addEventListener('offline', onConnectionChange);

  load();

  return () => {
    destroyed = true;
    window.removeEventListener('online', onConnectionChange);
    window.removeEventListener('offline', onConnectionChange);
    controller.abort();
  };
}
